### PR TITLE
feat: use history block to warn of unconfirmed sentences

### PR DESCRIPTION
**Pull request by HousewifeHacker**
I took a stab at https://github.com/Common-Voice/sentence-collector/issues/102 . I ran into an edge case during manual verification where if all of the sentences are filtered out, the UI and navigation flow are a little annoying. I think that's a separate issue though. This history block would start when the Submit button is clicked, and end when all the confirmation is done and state is reset. I think it would make sense to make the block start sooner, when the sentences-input has a value, but the code would be more complicated. What do you think?

### CODE REVIEW

**Comment by MichaelKohler** [comment]
Thanks for the PR. Yes, I agree that this would be indeed if it already would block when the sentence input is filled. This would help avoid losing already written sentences. Do you want to tackle this?

**Comment by MichaelKohler** [comment]
I have quickly tested this, would like to test some edge cases though. Will do that beginning of next week, thanks!

**Comment by HousewifeHacker** [comment]
I was on vacation. I can spend more time on this next week or near the end of this week. I would appreciate if you can describe the edge cases so that the fix is adequate and we can add tests for them

**Comment by MichaelKohler** [comment]
> I was on vacation. I can spend more time on this next week or near the end of this week. I would appreciate if you can describe the edge cases so that the fix is adequate and we can add tests for them

I wanted to test mostly around making sure it always gets unblocked when it needs to be. But thinking about it, that is indeed only after submission, before it shouldn't. I'd say all good!

Do you wanna tackle the improvement to also block when sentences are entered? Or do you wanna follow up with a second PR and we merge this one?

**Comment by HousewifeHacker** [comment]
I want to tackle the improvement and test coverage.

**Pull request merged**
