### PR TITLE
Checking whether the sentence contains [?!] in the middle

### PR DESCRIPTION
**Pull request by jotaro-sama**
As discussed in #202, I've added a check for those characters in the middle of a sentence as they mean it's two sentences. In the Italian version we already handled `.` in the middle so it now checks for `[?!.]`.

### CODE REVIEW

**Comment by MichaelNMaggs** [comment]
Please remove those checks from the middle of sentence. It's extremely common to have [?!] in the middle, for example:

"Where are you going?" he asked.
"Help!" she shouted.

**Comment by MichaelKohler** [comment]
I'll let @nukeador decide here.

**Comment by nukeador** [comment]
I think we shouldn't invalidate sentences with .?! in the middle, they are correct sentences and this would bring more difficult to collect sentences.

If you still this is needed, let's open a conversation on discourse and engage with deep speech experts to understand if this is needed or not.

Thanks!

**Comment by MichaelKohler** [comment]
This is reverted now (I've left it for the Italian validation though).

**Pull request merged**
