### PR TITLE
Mobile UI #164

### PR DESCRIPTION
**Pull request by alejandroclose**
Hi @MichaelKohler ! So this is my first pull request ever, sorry in advance if you find something that's not right, I still have a lot to learn! 

I've thought of different ways to make a hamburger menu but I couldn't find a way to make it work without a fixed navbar, so this pull request is the solution I came up with: if the user is on the website in a screen with a width bigger than 481px the website stays as it is right now. Meanwhile, if the user visits the page in a screen smaller then 480px, he/she will see a button on top of the content to hide the sidebar and have the main content of the page in full screen. 

I would really appreciate if you could give me feedback. I'm open to rewriting everything again!

Best regards, 

Alejandro.

### CODE REVIEW

**Comment by MichaelKohler** [comment]
Thanks a lot! I will have a look soon, I'm at a conference this weekend, so might not have time until Monday. 

For now, it seems to have some conflicts, can you make sure those are resolved? Merging in the newest changes from the master branch and resolving the resulting conflicts should do the trick. :)

**Comment by MichaelKohler** [comment]
Hi @alejandroclose did you close this PR on purpose? I see that the build failed, that was due to a line that was added mistakenly during the merge. I'm happy to reopen this PR and we can continue here, or you can open a new one, I'll leave this up to you. Tell me if you need any help :)

**Comment by alejandroclose** [comment]
Hi, @MichaelKohler  I closed it on purpose because I needed to change something else than the conflicts it had. But now, I'm having a problem that I don't know how to fix: merge from a new local branch to the master that is up to date with my fork.

**Comment by MichaelKohler** [comment]
Can you delete the localStorage item and then try again?

Screenshot 2019-06-03 at 12 42 43

(of course it would say "localhost" in your case)

If that doesn't help, can you send me the complete diff between your local branch and this repositories master branch?

What I usually do is the following:

* I keep my fork's master in sync with this repo's master branch
* Whenever I want to create a PR, I create a new local branch and make changes on that
* When I want to create a PR, I create it from my branch by pushing my new branch to my fork

This makes it quite easy to just discard a branch and my master will always be "clean".

**Pull request closed without merging**
