### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by abusarimhindi**
Updating for ur.js

### CODE REVIEW

**Comment by abusarimhindi** [comment]
Dear @MichaelKohler, I am not expert in coding and don't know any coding language, I came on GitHub to create pull request for my Urdu language, but I failed to create this, getting errors, and I couldn't understand where I am wrong.

For Urdu language limitation of 14 words is a problem, we need approx 25 words for a complete meaningful sentence.

I request you to please help me to create this PR.

**Comment by MichaelKohler** [comment]
The error here is expected, as the rest of the work is in another Pull Request. This is all good :)

**Comment by abusarimhindi** [comment]
When it will be merged, I am waiting for approval of my request. I want to start sentence collection work. Please clear the problem of this PR, if any.

**Pull request merged**
